### ISSUE TITLE
Incompatibility with Improved Redstone mod

### ISSUE THREAD

**Issue by darksoulq** [replaceitem/integrated-circuit#35]
Hello there, i really like this mod but im facing a terrible issue right now, while running this with the mod Improved Redstone on Fabric, it causes a crash!, this is the crash error: (this happens seemingly when i connect IC"s with redstone components from Improved Redstone)

```
net.minecraft.class_148: Exception while updating neighbours
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1025) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot set property class_2758{name=power, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to 30 on integrated_circuit:port, it is not an allowed value
        at net.minecraft.class_2688.method_11657(class_2688.java:129) ~[server-intermediary.jar:?]
        at net.replaceitem.integratedcircuit.circuit.ServerCircuit.onExternalPowerChanged(ServerCircuit.java:65) ~[integrated-circuit-1.21-1.5.0.jar:?]
        at net.replaceitem.integratedcircuit.circuit.context.BlockEntityServerCircuitContext.readExternalPower(BlockEntityServerCircuitContext.java:98) ~[integrated-circuit-1.21-1.5.0.jar:?]
        at net.replaceitem.integratedcircuit.IntegratedCircuitBlock.method_9612(IntegratedCircuitBlock.java:99) ~[integrated-circuit-1.21-1.5.0.jar:?]
        at net.minecraft.class_4970$class_4971.method_26181(class_4970.java:1113) ~[server-intermediary.jar:?]
        at net.minecraft.class_7165.method_41708(class_7165.java:42) ~[server-intermediary.jar:?]
        at net.minecraft.class_7159$class_7161.method_41707(class_7159.java:132) ~[server-intermediary.jar:?]
        at net.minecraft.class_7159.method_41702(class_7159.java:78) ~[server-intermediary.jar:?]
        at net.minecraft.class_7159.method_41706(class_7159.java:65) ~[server-intermediary.jar:?]
        at net.minecraft.class_7159.method_41704(class_7159.java:37) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_8492(class_3218.java:1054) ~[server-intermediary.jar:?]
        at net.minecraft.class_2312.method_9997(class_2312.java:193) ~[server-intermediary.jar:?]
        at net.minecraft.class_2312.method_9615(class_2312.java:176) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26182(class_4970.java:1137) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818.redirect$beb000$worldedit$setBlockStateHook(class_2818.java:5795) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818.method_12010(class_2818.java:273) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_30092(class_1937.java:232) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8652(class_1937.java:217) ~[server-intermediary.jar:?]
        at net.minecraft.class_2312.method_9588(class_2312.java:64) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1149) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_14189(class_3218.java:759) ~[server-intermediary.jar:?]
        at net.minecraft.class_6757.method_39390(class_6757.java:215) ~[server-intermediary.jar:?]
        at net.minecraft.class_6757.method_39377(class_6757.java:98) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:339) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[server-intermediary.jar:?]
        ... 5 more
    ```
    
    incase its a issue in Improved Redstone i have made sure to open an issue there too

**Comment by replaceitem** [comment]
Looks like that mod has signal strengths higher than 15, which when inputted, will try to set a wire inside the circuit to that which is not supported. I guess capping the signal strength at 15 would make sense.

**Comment by replaceitem** [comment]
Fixed in https://modrinth.com/mod/integrated-circuit/version/1.5.1

**Comment by darksoulq** [comment]
srsly sorry, ive been busy with studies, also really thank you!
